"""add purpose to phone_verification

Revision ID: e5187cfa2437
Revises: 0004
Create Date: 2026-03-21 15:40:05.575255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5187cfa2437'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_verifications', sa.Column('purpose', sa.String(length=32), server_default='registration', nullable=False))
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('phone_verifications', 'purpose')
    # ### end Alembic commands ###
